service: notify-booth-update

frameworkVersion: "=1.67.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${env:S3_BUCKET}
            - "/*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - schedule: rate(10 minutes)
    environment:
      BOOTH_URL: ${env:BOOTH_URL}
      S3_BUCKET: ${env:S3_BUCKET}
      S3_KEY: ${env:S3_KEY}
      SLACK_URL: ${env:SLACK_URL}
      SLACK_CHANNEL: ${env:SLACK_CHANNEL}

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET}
